version: '3.9'
services:
  app:
    image: node:latest
    container_name: inn-quizz
    restart: unless-stopped
    working_dir: /app
    network_mode: host
    volumes:
      - ./:/app
    command: bash -c "npm install; npm run dev --host"
